my solutions
mate-academy/js_style-to-object pull request #1175
Opened 2022-06-13 11:18 UTC by Pavlo000

2022-06-13 12:33 UTC, stanislav-topikha requested changes

2022-06-13 12:33 UTC, stanislav-topikha commented on src/convertToObject.js
> +  }
![image](https://user-images.githubusercontent.com/99331793/173354371-e8ba8400-1397-4972-ae38-f06a51492123.png)
no loops allowed

2022-06-14 09:07 UTC, stanislav-topikha approved these changes

2022-06-15 08:22 UTC, mykola-koval approved these changes

2024-11-26 18:21 UTC, closed without merging