solution
mate-academy/js_style-to-object pull request #1639
Opened 2022-11-28 19:46 UTC by lefteris-L

2022-11-29 12:10 UTC, UmizDemud approved these changes
I like it, separating by ';' is seems to be the right approach

2022-11-29 14:56 UTC, naziamoff requested changes

2022-11-29 14:56 UTC, naziamoff commented on src/convertToObject.js
> +  return pairs;
please use `map` `filter` and `reduce` methods to get some practice with them

2022-11-30 07:48 UTC, naziamoff approved these changes
🔥

2023-10-29 19:59 UTC, closed without merging