Develop
mate-academy/js_style-to-object pull request #1850
Opened 2023-01-31 13:54 UTC by vanyachyzh

2023-02-01 11:28 UTC, VitaliyBondarenko1982 requested changes

2023-02-01 11:28 UTC, VitaliyBondarenko1982 commented on src/convertToObject.js
> +  delete object[''];
Try to do it in reduce method. Or better make just one iteration and made everything in reduce instead map and reduce.

2023-02-01 16:32 UTC, etojeDenys approved these changes
LGTM

2023-02-02 10:47 UTC, VitaliyBondarenko1982 approved these changes
Good performance improvement!
You do not need to re-request review again, because this task is already approved 🙂

2024-03-07 18:43 UTC, closed without merging