Develop js_style-to-object
mate-academy/js_style-to-object pull request #1912
Opened 2023-02-22 13:45 UTC by sergey-lipikhin

2023-02-22 15:55 UTC, NataliaSavenets approved these changes

2023-02-22 16:20 UTC, sergii-nosachenko requested changes

2023-02-22 16:20 UTC, sergii-nosachenko commented on src/convertToObject.js
> +    ));
Use `reduce` instead. Accumulate props to an empty object.

2023-02-22 16:20 UTC, sergii-nosachenko commented on src/convertToObject.js
> +  const propertyValuePair = properties
```suggestion
  return sourceString
    .split(';')
```
Chain methods. Also, you don't need to have those variables. Just return the accumulated object.

2023-02-23 09:58 UTC, sergii-nosachenko approved these changes
Good work 🔥

2024-03-20 11:04 UTC, closed without merging