add solution
mate-academy/js_style-to-object pull request #2872
Opened 2023-12-25 10:40 UTC by YevhenOstrovskiy

2023-12-25 19:14 UTC, rtkachuk-moon approved these changes
👍

2023-12-26 11:28 UTC, DanilWeda requested changes
Good job! 
Check the test suite and some comments for improvement! 
Thanks!

2023-12-26 11:28 UTC, DanilWeda commented on src/convertToObject.js
> +    });
Try to use a method that returns an object!

2023-12-26 11:28 UTC, DanilWeda commented on src/convertToObject.js
> +      const value = part[1] ? part[1].trim() : '';
as alternative 
```suggestion
      const [key, value] = part;
```

2024-01-22 14:26 UTC, olya-shyian approved these changes
Wow, impressive!🔥

2024-09-01 16:45 UTC, closed without merging