Solution
mate-academy/js_style-to-object pull request #354
Opened 2020-09-30 10:21 UTC by andlap24

2020-09-30 12:20 UTC, xeilen requested changes
окей, код робочий)
але в нас тема Array iteration methods, а тут ти жодного не використав
думаю варто все ж додати декілька

2020-09-30 12:36 UTC, andlap24 commented
> окей, код робочий)
> але в нас тема Array iteration methods, а тут ти жодного не використав
> думаю варто все ж додати декілька

та да, є більш елегантні способи рішення

2020-09-30 12:38 UTC, xeilen approved these changes

2020-10-01 08:56 UTC, Vladimir-Beliy approved these changes

2026-02-15 13:24 UTC, closed without merging