solution
mate-academy/js_style-to-object pull request #382
Opened 2020-10-05 20:29 UTC by xipholena

2020-10-05 21:12 UTC, putsan requested changes
Гарно зроблено через методи!

2020-10-05 21:12 UTC, putsan commented on src/convertToObject.js
> +  const styleObj = {};
У назві змінної не повинно бути назви структури, ментори звертають увагу

2020-10-05 21:12 UTC, putsan commented on src/convertToObject.js
> +  const sourseArray = sourceString
тут також

2020-10-05 21:12 UTC, putsan commented on src/convertToObject.js
> +    styleObj[property] = value;
не часто сам таке роблю але якщо вже виправлятимеш назви то для красоти можна:
```suggestion
  sourseArray.forEach(item => {
    let { key, value } = item.split(':');
    key = key.trim();
    value = value.trim();

    styleObj[key] = value;
```
Хоча міг трохи помилитися з синтаксисом без едітора але переприсвоєння має спрацювати без лишніх змінних..

2020-10-06 10:09 UTC, xipholena commented on src/convertToObject.js
> +  const styleObj = {};
Моя постійна помилка)

2020-10-06 10:17 UTC, xipholena commented on src/convertToObject.js
> +    styleObj[property] = value;
я їх називала згідно того, яквони називаються у Цсс, але сама не дуже впевнена, що пам"ятаю їх правильно, тому краще перейменую до ключів, значень та властивостей, напевно

2020-10-06 10:54 UTC, putsan approved these changes

2020-10-06 13:10 UTC, solaryasha approved these changes

2020-12-19 15:24 UTC, closed without merging