solution
mate-academy/js_style-to-object pull request #557
Opened 2021-05-04 06:28 UTC by Andriykooo

2021-05-04 19:52 UTC, Dima-Batiuk approved these changes
Nice! )

2021-05-05 07:34 UTC, aliceblunt8 requested changes

2021-05-05 07:34 UTC, aliceblunt8 commented on src/convertToObject.js
> +    .map(element => element.split(':').map(word => word.trim()));
```suggestion
  const parameters = sourceString
    .split(';')
    .map(element => element
      .split(':')
      .map(word => word.trim())
    );
```

2021-05-05 07:34 UTC, aliceblunt8 commented on src/convertToObject.js
> +  };
use forEach here

2021-05-05 12:29 UTC, aliceblunt8 approved these changes

2021-05-05 12:29 UTC, aliceblunt8 commented on src/convertToObject.js
> +  const styles = {};
```suggestion
  const styles = {};
  
```

2022-09-21 14:58 UTC, closed without merging