solution
mate-academy/js_style-to-object pull request #896
Opened 2021-12-22 19:28 UTC by mykola-koval

2021-12-22 20:14 UTC, sergeyglazgo approved these changes

2021-12-23 10:52 UTC, danheim requested changes

2021-12-23 10:52 UTC, danheim commented on src/convertToObject.js
> +  const x = sourceString
terrible variable name

2021-12-28 14:03 UTC, danheim approved these changes

2023-03-02 06:05 UTC, closed without merging