solution
mate-academy/js_style-to-object pull request #997
Opened 2022-02-17 15:26 UTC by VladBrynzia

2022-02-17 15:45 UTC, addKiwi approved these changes
Good Job 🔥

2022-02-17 15:45 UTC, addKiwi commented on src/convertToObject.js
> +  return cssRule;
```suggestion
  const cssRule = sourceString
    .split(';')
    .map(element => element.split(':'))
    .filter(empty => empty.length > 1)
    .reduce(
      (resultCssObj, [keys, value]) => {
        resultCssObj[keys.trim()] = value.trim();

        return resultCssObj;
      }, {});

  return cssRule;
```
Looks better

2022-02-17 15:49 UTC, solaryasha requested changes

2022-02-17 15:49 UTC, solaryasha commented on src/convertToObject.js
> +  return cssRule;
```suggestion
    return sourceString
      .split(';')
      .map(element => element.split(':'))
      .filter(empty => empty.length > 1)
      .reduce(
         (resultCssObj, [keys, value]) => {
        resultCssObj[keys.trim()] = value.trim();

        return resultCssObj;
      }, {});
```

Even better

2022-02-17 15:49 UTC, solaryasha commented on src/convertToObject.js
> +      (resultCssObj, [keys, value]) => {
https://mateacademy.slack.com/archives/C02T596SHUZ/p1644845021054899

2022-02-18 07:18 UTC, solaryasha approved these changes

2022-02-18 07:18 UTC, solaryasha commented on src/convertToObject.js
> +  return cssRule;
Я би одразу повертав значення, але можна і так

2022-12-14 15:37 UTC, closed without merging